### ISSUE TITLE
Review static website generators

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#1]
Here are my notes on [this top 10 list of static website generators](https://www.netlify.com/blog/2016/05/02/top-ten-static-website-generators/) (and some honorable mentions):

* Jekyll: Ruby, very popular. **Good candidate**
* Hexo: nodeJS. According to @timrobertson100, nodeJS has very fast development, better to avoid for this use case.
* Hugo: Go. No Go familiarity in TDWG.
* Octopress: Ruby, based on Jekyll. Might as well use Jekyll.
* Pelican: Python. Python knowledge present in TDWG. Pelican already tested by @peterdesmet and Hilmar Lapp. **Good candidate**
* Brunch: more like a build tool for apps
* Middleman: more for high end complex websites
* Metalsmith: requires technical proficiency
* Harp: more like build tool
* Exposé: for photos
* Gatsby: better for single page apps
* Roots: nodeJS. Avoid use of nodeJS
* GitBook: for eBooks
* Cactus: Python (Django), S3 deployment. Younger than Pelican, smaller community.

---

Conclusion: **Pelican** (maybe Cactus) in Python and **Jekyll** (maybe Octopress) in Ruby are both good candidates. Because of the familiarity with both Python and Pelican for some members in the TDWG community, the fact that the site will be deployed on a GBIF server (so close integration with GitHub pages is less important) and limited resources, we (@peterdesmet and @timrobertson100) opted to go for Pelican, rather than fully compare the two options. If we notice that approach is a dead end, we can still opt for Jekyll: the Markdown content should be easy to switch.

**Comment by csparr** [comment]
Can this be closed because you have chosen Pelican?
