### ISSUE TITLE
consistent formatting

### ISSUE THREAD

**Issue by gkampmeier** [tdwg/website#108]
**Page(s) where issue occurs**

> https://www.tdwg.org/about/executive/2019/

**Issue description**

> Not all names of candidates appear with same call-out styling (orange)

**Comment by stanblum** [comment]
Orange text indicates a link.  Quentin added links to a nominee's ORCID page (like a bio).  People without a link don't have an ORCID page.  Should we raise this discrepancy among nominees in the Exec call?

**Comment by peterdesmet** [comment]
Note that on the mentioned 2019 executive page, all members have a mailto link, except one (Connie Rinaldo): https://www.tdwg.org/about/executive/2019/

On the current executive page, all members have a link: https://www.tdwg.org/about/executive/

I think we can close this issue.
