### ISSUE TITLE
Do we want title capitalization?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#13]
How do we want to capitalize titles on the TDWG website? Some examples

> Our mission
> Our Mission
>
> Natural collections descriptions (NCD): A data standard for exchanging data describing natural history collections
> Natural Collections Descriptions (NCD): A Data Standard for Exchanging Data Describing Natural History Collections
> Natural Collections Descriptions (NCD): A Data Standard For Exchanging Data Describing Natural History Collections
>
> Biodiversity informatics curriculum interest group
> Biodiversity Informatics Curriculum Interest Group

Personally, I'm not a big fan of capitalizing (the heading and font size should be indication enough), but some people might think different. There are [different ways](http://titlecapitalization.com) of doing this, I just like it to be consistent, so we can add it to the contributing guidelines.

**Comment by dkoureas** [comment]
Persistence is the most important here.

I would argue that the Words corresponding to given acronyms need to be capitalised though. So I would go with
Natural Collections Descriptions (NCD): A Data Standard for Exchanging Data Describing Natural History Collections

Kind regards,
Dimitris



--

Dr Dimitrios Koureas, FLS

Lead, Research Data & Partnerships
Dept of Life Sciences | Natural History Museum London | SW7 5BD London, UK
Coordinator, Distributed System of Scientific Collections (DiSSCo) initiative
Chair, Biodiversity Information Standards (TDWG)
co-Chair, RDA – BDI IG & ASDOC WG

ORCID: 0000-0002-4842-6487 | Linkedin: uk.linkedin.com/in/dkoureas
E-mail: d.koureas@nhm.ac.uk | Twitter: @DimitrisKoureas | Tel: +44 (0) 207 942 5244



________________________________

**Comment by gkampmeier** [comment]
I agree absolutely with capitalizing the first letters of words corresponding to given acronyms. After the colon, however I don't think that in general the words following it should be capitalized  [https://www.grammarly.com/blog/capitalization-after-colons/](https://www.grammarly.com/blog/capitalization-after-colons/)

As for titles (Our Mission), I think it depends on the heading level and how it is nested on the site. In general, principle headings for the page should have all principle words are capitalized and if a colon is used, follow the rules of capitalization after colons. Subheadings may either be featured as differently styled text and/or with different rules of capitalization, e.g.

# Our Mission
## In the Beginning
### _Founders thought_

My 2 cents
Gail

**Comment by peterdesmet** [comment]
Thanks!

Any easy to follow guidelines out there we can reference (which cover more than after colon)? E.g. I'm not 100% what "principle words" are.

I'd use the same rules for all headings...

**Comment by gkampmeier** [comment]
[https://capitalizemytitle.com/](https://capitalizemytitle.com/) where "principle" = "important"

Elsewhere the smallest rule of thumb I've seen is don't capitalize words under three letters, but obviously pronouns and subordinating conjunctions are in a grey area in that simple rule. I would have included the subordinating conjunctions in the categories of things not capitalized.

**Comment by peterdesmet** [comment]
Ooh, I do like "Sentence case" 😄  It's simple an easy to remember:

> The other major type of title capitalization standard is sentence case. **Sentence case simply means you capitalize the first letter of a sentence and nothing else.** It is the same across all of the four styles.

We could also adopt that, with the note that spelled-out acronyms need to retain their capital letters.

**Comment by timrobertson100** [comment]
The guidelines we received from our comms at GBIF (ex-BBC guy) was sentence case and capitalize acronyms and names only (e.g. data standards is not (?) used an acronym so wouldn't be randomly capitalized, which Darwin Core would be).  

# Our mission

# In the beginning

Natural Collections Descriptions (NCD): A data standard for exchanging data describing natural history collections

**Comment by gkampmeier** [comment]
Sounds like a good fit (has international guidelines befitting an international organization) and will have fewer rules (to please our number one web guru ;) )!

**Comment by stanblum** [comment]
I'm not sure I'm following your examples, but to my mind, "Darwin Core" is
a proper name and should be capitalized.

**Comment by gkampmeier** [comment]
I _think_ that Tim said that Darwin Core would be capitalized, but interestingly, we use DwC as an acronym, not DC.

**Comment by stanblum** [comment]
DC is commonly understood to be Dublin Core

**Comment by peterdesmet** [comment]
_This is an old issue regarding the TDWG (Pelican) website. I am trying to clean those up._

Capitalization was discussed at https://github.com/tdwg/website-migration-2022/issues/27. We opted for `Sentence case`, not `Title Case` except for official TDWG names.
