### ISSUE TITLE
Functional subcommittee links broken

### ISSUE THREAD

**Issue by nickynicolson** [tdwg/website#134]
**Page(s) where issue occurs**

https://www.tdwg.org/about/executive/

**Issue description**

Functional subcommittee links broken. They point to links in the form:
 https://www.tdwg.org/committees/tag/
The correct format seems to be:
 https://www.tdwg.org/about/committees/tag/

> What is wrong? What were you expecting instead?

**Comment by stanblum** [comment]
Thanks, Nicky!  Fixed.
