### ISSUE TITLE
How to display email addresses?

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#14]
There's currently a mixture of how email addresses are displayed on the TDWG site:

1. Difficult to read, but with a regular address behind link ([this page](http://www.tdwg.org/about-tdwg/executive/exec-comm-2017/)):

> [d.koureas (at) nhm (dot) ac (dot) uk](mailto:d.koureas@nhm.ac.uk)

2. `@` symbol written differently and inconsistently, and some JavaScript to obfuscate address in link (doesn't show up in this issue, but see [this page](http://www.tdwg.org/activities/bdi-curriculum-ig/charter/)):

> [hanna.koivula [at] iki.fi](javascript:linkTo_UnCryptMailto('ocknvq,jcppc0mqkxwncBkmk0hk');)
> [hanna.koivula(at)iki.fi](javascript:linkTo_UnCryptMailto('ocknvq,jcppc0mqkxwncBkmk0hk');)

3. Written (almost) as regular address that can be copied, but no link ([this page](http://www.tdwg.org/about-tdwg/executive/exec-comm-2017/)):

> james.macklin(at)agr.gc.ca

Let's choose one for consistency!

My 2 cents: option 3, but with regular `@` symbol: `james.macklin@agr.gc.ca`. It's intuitive to add, maintain and use. I never click email links, because it more often than not opens an email program I'm not using; so I copy the address. I'm also assuming crawlers are pretty powerful and that my address is out there somewhere... relying on a good spam filter to keep unwanted email at bay.

Feedback welcome.

**Comment by gkampmeier** [comment]
I agree, we should choose one.  I wondered, however, if web crawlers weren't sophisticated enough to see through these obfuscations that mainly only annoy legitimate users. This rather agreed with what I was thinking [https://qz.com/181635/surprise-theres-really-no-need-to-conceal-your-email-address-from-spammers/](https://qz.com/181635/surprise-theres-really-no-need-to-conceal-your-email-address-from-spammers/).  There is apparently another way suggested, although less handy, unless what you are doing can be programmed to be used automatically by anyone creating a webpage for our site [https://stackoverflow.com/questions/4098408/is-it-worth-obfuscating-email-addresses-on-the-web-these-days?noredirect=1&lq=1](https://stackoverflow.com/questions/4098408/is-it-worth-obfuscating-email-addresses-on-the-web-these-days?noredirect=1&lq=1).

**Comment by peterdesmet** [comment]
_This is an old issue regarding the TDWG (Pelican) website. I am trying to clean those up._

Email addresses are shown as regular email addresses on the site for most pages. Very few were still written as `name [at] something.org`, which I have changed to regular email addresses for consistency and ease of use.
