### ISSUE TITLE
CSS not found when generating locally

### ISSUE THREAD

**Issue by balbertini** [tdwg/website#17]
Followed build site procedure. CSS on main page is being referenced as:

    <link rel="stylesheet" href="/theme/css/main.css">

If using relative paths, it should be:

    <link rel="stylesheet" href="theme/css/main.css">

and modifying this on the generated output fixed the issue.

Alternatively, use abesoure path, but not sure about the mess that it could cause on local/test deploys.

**Comment by peterdesmet** [comment]
Thanks for the reviewing the build procedure. You're right. The actual href is `{{ SITEURL }}/theme/css/main.css`, but on local dev `SITEURL` is empty:

https://github.com/tdwg/website/blob/1db30f1284f1231802276d59ac42790b7179e0c3/settings.py#L53

Which results in `/theme/css/main.css`. When you open `output/index.html` it indeed doesn't find the CSS. It does if I'm running a local server from the `output` dir: `python -m http.server 8000`.

One potential solution is to include the slash in `SITEURL`. @mattblissett, is it a good idea to include the end slash in `SITEURL`, like `https://dev.tdwg.org/` ?

**Comment by peterdesmet** [comment]
Pelican convention is to not include the trailing slash though: http://docs.getpelican.com/en/stable/settings.html#SITEURL

**Comment by peterdesmet** [comment]
Closing this issue: best course of action to test locally is to use `python -m http.server 8000` as written in the README: https://github.com/tdwg/website#build-site
