### ISSUE TITLE
Preferred build process

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#2]
@timrobertson100 any preference for the build process? With Pelican, a site can be generated with:

1. `pelican` 
2. `fab`
3. `make`

See [the documentation](http://docs.getpelican.com/en/stable/publish.html#automation) for more info. I'd opt for `pelican` as that limits the number of settings files to maintain, but you might have good reasons to prefer any of the other two. Let me know.

**Comment by MattBlissett** [comment]
Pelican seems to work fine. I only have basic Python knowledge, so I'll trust your judgement.

I'm using a Python 3 virtual environment:

```
python3 -m venv tdwgenv
source tdwgenv/bin/activate
pip install pelican markdown beautifulsoup4
```
