### ISSUE TITLE
Committee nominations (2020): deputy chair missing from description list

### ISSUE THREAD

**Issue by nickynicolson** [tdwg/website#248]
**Page(s) where issue occurs**

https://www.tdwg.org/news/2020/call-for-nominations/

**Issue description**

Deputy chair is open for nominations but is not described in the "Offices open for election" listing further down the page

**Comment by qgroom** [comment]
Good point!
I'll fix it ASAP

**Comment by qgroom** [comment]
The page has been updated now.
Thanks for pointing it out!
