### ISSUE TITLE
Introduction to TDWG for homepage

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#25]
The [homepage](https://dev.tdwg.org/) describes TDWG in a title and short description (feedback welcome):

> # Biodiversity Information Standards (TDWG)
> 
> We are a non-profit organization and community dedicated to developing biodiversity information standards

But below that, we need an introduction to TDWG that expands on that a bit, ideally linking to different sections (Standards, Journal, Community) of the website in the text. It shouldn't be more than a paragraph. @gkampmeier @dkoureas @stanblum can you provide one? Inspiration:

## Introduction in [constitution](https://dev.tdwg.org/about/constitution/)

> The International Working Group on Taxonomic Databases (herein called "TDWG") is a not-for-profit, scientific and educational association formed to establish international collaboration among the creators, managers and users of biodiversity information so as to promote the wider and more effective dissemination of information about the world's heritage of biological organisms for the benefit of the world at large.
> 
> To achieve its goals, TDWG
> 
> 1. develops, adopts and promotes standards and guidelines for the recording and exchange of data about organisms;
> 2. promotes their use through the most appropriate and effective means;
> 3. acts as a forum for discussion through holding meetings and through publication and
> 4. undertakes any other activities that are judged useful to the organisation.

## Description at [fairsharing.org](https://fairsharing.org/collection/TDWGBiodiversity)

> Biodiversity Information Standards (TDWG), also known as the Taxonomic Databases Working Group, is a not for profit scientific and educational association that is affiliated with the International Union of Biological Sciences. TDWG was formed to establish international collaboration among biological database projects. TDWG promoted the wider and more effective dissemination of information about the World's heritage of biological organisms for the benefit of the world at large. Biodiversity Information Standards (TDWG) now focuses on the development of standards for the exchange of biological/biodiversity data. The TDWG develops, adopts and promotes standards and guidelines for the recording and exchange of data about organisms. Additionally, it promotes the use of standards through the most appropriate and effective means. The TDWG acts as a forum for discussion through holding meetings and through publications.

That last sentence could already link to `conferences` and `journal`.

**Comment by gkampmeier** [comment]
![screen shot 2018-03-15 at 8 11 28 am](https://user-images.githubusercontent.com/9611386/37465337-dfbbf516-2828-11e8-80f8-4f5314fa2ac9.png)
We are using the term (biodiversity information standards) as part of the definition. On possibility is changing to "An international non-profit organization dedicated to developing ways to share biological data"  As a tag line, it doesn't have to be folksy (i.e. "We are..." although I can appreciate the sentiment for approachability), but it should in some way explain what biodiversity information standards are/do. I also think it's important to include the fact that it's international here, over community, and try to convey the community in the text below that. For better or worse we are an organization (note this word is spelled with a 'z' here and further below, but an 's' also in the text). Not sure whether we should choose a [standard spelling](https://www.theatlantic.com/international/archive/2012/10/a-call-for-spelling-standardization-or-is-that-standardisation/263091/) and stick with it or what.

**Comment by peterdesmet** [comment]
Thanks for feedback on the tagline @gkampmeier. I'd like to keep the "We are ..." Based on your suggestion, we could do:

> 1. We are an international non-profit organization dedicated to developing ways to share biological data
> 2. We are an international non-profit organization dedicated to developing standards to share biological data
> 3. We are an international non-profit organization dedicated to improve how we share biological data
> 4. We are an international non-profit organization dedicated to improve the interoperability of biological data

Feedback?

- Separate issue for spelling #26
- Issue on paragraph below still stands.

**Comment by gkampmeier** [comment]
I know I'm dabbling at the edges, and I'll get to the meat soon, but the box calling out the annual meeting also needs revision (for me, subscriptions are for journals/magazines). "Registration is now open for the TDWG Annual Conference in Dunedin, NZ." If there is room, adding something about "...held jointly with the Society for the Preservation of Natural History Collections (SPNHC)."

**Comment by gkampmeier** [comment]
Regarding your suggestions for rewording the tag line:
1 &3. although "ways" doesn't sound very specific, it was purposeful. Question is the difference between 1 and 3 of "developing ways" vs. "improving how." These are presupposing two starting points, and I suppose it could be argued that we've already developed ways and are now concentrating on improving how...??
2. uses part of the phrase we are trying to define in the definition still ("standards")
3 & 4. "improve" would have to be "improving"
4. "interoperability" is more jargon-y --if you're going to be approachable by using "We are" then you need to use words that ordinary people might use. 

Personally, I still also stand by losing the "We are" in favor of something shorter in this space.

**Comment by gkampmeier** [comment]
Suggest the following edits to the introduction:

Historically known as Taxonomic Databases Working Group, today's Biodiversity Information Standards (TDWG) is a not-for-profit, scientific and educational association formed to establish international collaboration among the creators, managers and users of biodiversity information and to promote the wider and more effective dissemination and sharing of knowledge about the world's heritage of biological organisms.

To achieve its goals, TDWG
- develops, adopts and promotes standards and guidelines for the recording and exchange of data about organisms;
- promotes the use of these standards and guidelines through the most appropriate and effective means; and
- acts as a community forum for discussion through meetings, online discussions, and publications.

**Comment by peterdesmet** [comment]
I've just updated the homepage intro text with the suggestions by @gkampmeier: 652ecb21ca0db4614f38988a784bbf193a9c4c27

@dkoureas @stanblum Close if you agree.

**Comment by stanblum** [comment]
I tightened the introductory bullets and some of the wording a while ago.  Closing this.
