### ISSUE TITLE
Choose English spelling variant

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#26]
In response to @gkampmeier [comment](https://github.com/tdwg/website/issues/25#issuecomment-373379507): we need to choose a English spelling variant:

1. British English with "-ise"
2. British English with "-ize" (Oxford spelling)
3. American English

See [this Wikipedia section](https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Spelling#International_organizations) on which organizations use what: e.g. International Organization for Standardization (ISO) uses British English with "-ize" and that is what I use as well.

We (website editors or @tdwg/exec) need to choose one soon and stick to it.

**Comment by MattBlissett** [comment]
For what it's worth, GBIF follows UN spelling, so number 2.

http://dd.dgacm.org/editorialmanual/ed-guidelines/style/spelling.htm

**Comment by dkoureas** [comment]
I would go with option 2 as well

Kind regards,
Dimitris

*--*

*Dr Dimitris Koureas, FLS*

Head, Department of International Cooperation on Biodiversity
Infrastructures
*Naturalis Biodiversity Center *
P.O. Box 9517, 2300 RA Leiden, NL

Coordinator, Distributed System of Scientific Collections (DiSSCo
<http://dissco.eu>)
Chair, Biodiversity Information Standards Organisation (TDWG
<http://tdwg.org>)

*ORCID*: 0000-0002-4842-6487 | *Linkedin*: linkedin.com/in/dkoureas
*Twitter*: @DimitrisKoureas | *Tel*: +31 (0) 71 751 9251
Meeting requests https://doodle.com/dimitriskoureas

**Comment by peterdesmet** [comment]
I'd say one more vote for option 2 and it is decided. 😄

**Comment by timrobertson100** [comment]
option 2

**Comment by peterdesmet** [comment]
Added to contributing guide: https://github.com/tdwg/website/commit/a3e5d4ce2512f5b904c08d0a06334111a6a3d956
