### ISSUE TITLE
YAML header for some pages malformed

### ISSUE THREAD

**Issue by nickynicolson** [tdwg/website#263]
The source for the following pages has malformed YAML headers (values are not quoted when they contain special characters like ':'):

- content/pages/standards/abcd/index.md
- content/pages/standards/sds/index.md
- content/pages/standards/tl-2/index.md
- content/pages/standards/vms/index.md

As the pages function correctly Pelican must tolerate this, but it prevents programmatic extraction of metadata from pages.

**Comment by stanblum** [comment]
Thanks, Nicky.  All those unquoted values are now fixed, but the
unfortunate thing is that the double quotes now print out as part of the
summary value. That's not great from a style perspective.  :-/  Also
unfortunately, modifying that is beyond my skill level (and perhaps even
access permissions).  Can I persuade anyone with more technical skill to
insert a quote-stripping regex in front of the write summary statement?

TIA  -Stan

**Comment by nickynicolson** [comment]
I'm happy for you to roll back this change to fix this rather than quote-stripping because the frontmatter actually isn't YAML, just a look-alike. There is a pelican plugin that uses YAML which we could install (I have it running locally) - this would be a better long term solution.

**Comment by peterdesmet** [comment]
The `description` (previously `summary`) for all pages now starts with `>`:

https://github.com/tdwg/website/blob/6ac7e2ef8e55e8f2d329f857f75268bf08264df9/standards/abcd/index.md?plain=1#L3-L4

- The `>` will combine multiple lines into one, but that feature is currently not used (the descriptions are one line, just like paragraphs in the text).
- The entire `description` will be interpreted as a Markdown paragraph.
- There is no need to quote the entire description, but doing so won't show the wrapping quotes on the site.
- It is possible to quote single words as is (no need to escape), those will be shown in curly quotes on the site.

Here's how the mentioned pages currently look:

https://www.tdwg.org/standards/abcd/
https://www.tdwg.org/standards/sds/
https://www.tdwg.org/standards/tl-2/
https://www.tdwg.org/standards/vms/

Closing this issue.
