### ISSUE TITLE
How to place Task Groups on Interest Group Page

### ISSUE THREAD

**Issue by gdadade** [tdwg/website#282]
**GBWG Interest Group**

> https://www.tdwg.org/community/gbwg/

We would like to place the Task Force(s) higher up on the page. I can add the header "Task Forces" below "Motivation and Scope", but what markup syntax do I have to use to move the TF thumbnail(s) to this spot?

**Comment by gkampmeier** [comment]
I think the TF thumbnails are automatically generated from the type of heading, so clicking on Edit this page should reveal the types of markup required to add the proper header.

**Comment by peterdesmet** [comment]
@gdadade the thumbnails are on the bottom by default. But you can force it to a specific place by adding :

```
<!-- subpages -->
```

I have done so in https://github.com/tdwg/website/pull/283. @gkampmeier can you review and accept?

**Comment by gdadade** [comment]
ok thanks! I made the edits and created a pull request :)

**Comment by peterdesmet** [comment]
Ok, resolved.
