### ISSUE TITLE
Test archiving of conference files

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#30]
After discussion with @timrobertson100: test archival of conference files (e.g. programme, presentations) in a separate repository `conferences-archive`:

```
2007/
    presentations/
    programme/
    docs/
```

_Note: archival might not be necessary for 2017 and later where BISS is used._

Website page for that conference should have basic information about conference (dates, location, organizers, website) and link to those files.

@peterdesmet will test this procedure for 2 conferences and request feedback.

**Comment by peterdesmet** [comment]
File size will be too large for a GitHub repo. 2008 conference alone = 978MB vs max allowed for repository = 1GB. Google Drive/Dropbox are annoying for deep linking, Zenodo does not allow directories or changes (without creating a new version), so decided with @timrobertson100 @MattBlissett to setup file server at GBIF.

**Comment by peterdesmet** [comment]
If anyone wants to contribute to the archive of TDWG conference documents, please let me know in this issue.

**Comment by MattBlissett** [comment]
[tdwg-conference-archive.txt](https://github.com/tdwg/website/files/1825847/tdwg-conference-archive.txt)

There is already a lot of this (4GB) on the filesystem of the existing server. Output of "tree" attached.

**Comment by peterdesmet** [comment]
Thanks @MattBlissett, will use that file to know how far along the archiving I am. Since there is some file management required (e.g. lots of directories we no longer need), I'll download and archive them on Google Drive first and then we can move everything to a file server.

**Comment by peterdesmet** [comment]
Hi @MattBlissett, we have archived most conference files and it would be good to setup a file server for those. I'll email you.

**Comment by peterdesmet** [comment]
I believe all conf files are now served from static.tdwg.org.
