### ISSUE TITLE
Logo missing

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#464]
**Page(s) where issue occurs**

https://www.tdwg.org/about/logos/

**Issue description**

The short form logo in white is missing in SVG: https://static.tdwg.org/logo/White/SVG/TDWG-Logo_Short-Form-white.svg

**Comment by peterdesmet** [comment]
Don’t need it, just wondered why it was missing.

**Comment by stanblum** [comment]
All versions have been posted and links are working.
