### ISSUE TITLE
TDWG 2017 and 2018 conference website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#488]
Ping @dshorthouse @jmacklin @stanblum @gkampmeier 

## Issue

I stumbled upon the **TDWG 2017 Annual Conference (Ottawa, Canada)** website at https://tdwg.github.io/conferences/2017/

I believe this website was created before the main TDWG website was using a static website generator and was therefore hosted from a separate repository, i.e. in the [tdwg.github.io repository](https://github.com/tdwg/tdwg.github.io). The site has its own layout and all pages render as excepted.

![TDWG-2017-Annual-Conference](https://user-images.githubusercontent.com/600993/216761490-f908cba8-01d3-49c2-98c0-ed5cb2efe7f9.png)

The site is however not linked to from the conference landing page on the main website https://www.tdwg.org/conferences/2017/ The page currently lists the following:

> Host
> : [Agriculture and Agri-Food Canada](http://www.agr.gc.ca/eng/home/?id=1395690825741)
> : [Canadian Museum of Nature](https://nature.ca/en/home)
> 
> Venue
> : [Delta Hotels Ottawa City Centre by Marriott](http://www.marriott.com/hotels/travel/yowdm-delta-hotels-ottawa-city-centre/) > in Ottawa, Canada
> 
> Date
> : 2-6 October 2017
> 
> Proceedings
> : published in [Biodiversity Information Science and Standards](https://biss.pensoft.net/collection/25/)
> 
> Programme
> : [TDWG 2017 programme](https://static.tdwg.org/conferences/2017/tdwg_2017_programme.pdf)

## Question

- Should this website be retained?
- Should we link to this website from https://www.tdwg.org/conferences/2017/

## Suggested actions

If we indeed keep it, then I propose:

- [x] To **not** integrate this site in the main TDWG website (it has it's own design and it will be easier to keep it that way)
- [x] To move the content to a dedicated `conference-2017` repo
- [x] Use the `tdwg.github.io` repo (where the site is currently) to redirect pages (see e.g. https://github.com/inbo/inbo.github.io#readme)
- [x] To setup a redirect for https://tdwg.github.io/conferences/2017/ to the new location at `https://tdwg.github.io/conference-2017`
- [ ] Add logo to https://www.tdwg.org/conferences/2017/

The repo also contains some initial content for the **TDWG 2018 Annual Conference (Dunedin, New Zealand)** at https://github.com/tdwg/tdwg.github.io/tree/master/conferences/2018, but

- Those pages are not hosted (e.g. https://tdwg.github.io/conferences/2018/call-for-abstracts/ returns a 404)
- The eventual TDWG 2018  was hosted from [http://spnhc-tdwg2018.nz/](https://web.archive.org/web/20181221215058/http://spnhc-tdwg2018.nz/) (URL no longer functions, link goes to Internet Archive)

- [x] I suggest to remove the initial TDWG 2018 content that was created in `tdwg.github.io`

**Comment by gkampmeier** [comment]
## Suggested actions
Agree with: 

- [ X]  To not integrate this site in the main TDWG website (it has it's own design and it will be easier to keep it that way)
- [X ]  To move the content to a dedicated conference-2017 repo [see below]

I am not sure I understand the implications of the following (e.g., is a redirect voluntary or involuntary for the user or is this preserving the content/format in a different place? Who has access to maintain (e.g., potential broken links) any redirected pages?)
- [ ]  Use the tdwg.github.io repo (where the site is currently) to redirect pages (see e.g. https://github.com/inbo/inbo.github.io#readme)
- [ ]  To setup a redirect for https://tdwg.github.io/conferences/2017/ to the new location at https://tdwg.github.io/conference-2017

## Comments
@dshorthouse I would love it if the current [conference site](https://www.tdwg.org/conferences/2017/) for 2017 could feature the beautiful fiery logo from that conference, whether or not a link to the original conference page is maintained.  @peterdesmet is this one of the files in static?  

I don't know how long the original site would be available (or the links checked to be current) but if the logos for hosts and sponsors can also be featured on TDWG's current conference website, this would also be good PR and a record of support for our history. Whether or not we link to [https://tdwg.github.io/conferences/2017/](https://tdwg.github.io/conferences/2017/) or not, the bits not featured in our current Conferences listing should be incorporated where practical.

The conference site https://tdwg.github.io/conferences/2017/ includes information that is outdated (e.g., registration link) but the twitter feed (link should be updated to [https://twitter.com/hashtag/tdwg17?f=live](https://twitter.com/hashtag/tdwg17?f=live) as it is now old and nothing comes up) is also a wonderful glimpse that should be featured on our current conference site(s).

**Comment by stanblum** [comment]
The website for the 2018 joint meeting was split between the local
committee and TDWG.  I think some of the content from the TDWG side is
worth keeping.  For the scientific record, we should keep the sessions and
their abstracts:

   - https://tdwg.github.io/conferences/2018/sessions/

Gail might want to keep some of the other content -- either available or
archived (not deleted/lost) -- because it tells us where we've come from.

From 2017, most of the pages are still available, and even SCHED has not
deleted our content from their site, so the embedding of the
schedule/program still works.

Unfortunately the recordings were lost. They were on the iDigBio account
with whatever service they were using (WebEx?), but stored in a piecemeal
structure with about six files needing to be integrated to make the whole.
We didn't have anyone with the skills to do that, so -- poof, recordings be
gone.

With a little work, the remaining stuff from 2017 could be cleaned up
(remove dead links and unnecessary pages); perhaps reformat things to make
the presentation more easily understandable.

I don't know what can be done to make the style of these old conferences
become more consistent with each other or the current website.

**Comment by peterdesmet** [comment]
## TDWG 2017

- Content now lives in dedicate repo (keeping entire history): https://github.com/tdwg/conference-2017
- Content is served from http://2017.tdwg.org (a GitHub Pages site)
- Old URL will redirect to site: https://tdwg.github.io/conferences/2017/

## TDWG 2018

- Content now lives in dedicate repo (keeping entire history): https://github.com/tdwg/conference-2018
- Content is served from http://2018.tdwg.org (a GitHub Pages site)
- Old URL will redirect to site: https://tdwg.github.io/conferences/2018/

## tdwg.github.io

- Repository is emptied and now only serves to redirect old URLs (as explained in README): https://github.com/tdwg/tdwg.github.io
