### ISSUE TITLE
Error Pages

### ISSUE THREAD

**Issue by ben-norton** [tdwg/website#492]
I crawled the TDWG website to locate broken links and error pages. The crawl scanned 196 pages and found only 15 errors. These are as follows:

URL | Error | Referral URL
-- | -- | --
https://www.tdwg.org/community/citizen-science/joel.sachs@agr.gc.ca | Url Check - Status code: 404 | https://www.tdwg.org/community/citizen-science/
https://www.tdwg.org/community/citizen-science/saraiva@usp.br | Url Check - Status code: 404 | https://www.tdwg.org/community/citizen-science/
https://www.tdwg.org/conferences/2022/session-list/lien.reyserhove@inbo.be | Url Check - Status code: 404 | https://www.tdwg.org/conferences/2022/session-list/
https://www.tdwg.org/activities/abcd/ | Url Check - Status code: 404 | http://www.tdwg.org/activities/abcd/
https://www.tdwg.org/conferences/2020/es/session-list/ | Url Check - Status code: 404 | https://www.tdwg.org/conferences/2020/es/
https://www.tdwg.org/community/mobs/sdavidson@orn.mpg.de | Url Check - Status code: 404 | https://www.tdwg.org/community/mobs/
https://www.tdwg.org/community/citizen-science/stk2@cornell.edu | Url Check - Status code: 404 | https://www.tdwg.org/community/citizen-science/
https://www.tdwg.org/community/osr/humboldt-core/ | Url Check - Status code: 404 | https://www.tdwg.org/conferences/2021/session-list/
https://www.tdwg.org/community/citizen-science/amast@bio.fsu.edu | Url Check - Status code: 404 | https://www.tdwg.org/community/citizen-science/
https://www.tdwg.org/conferences/2022/session-list/quentin.groom@plantentuinmeise.be | Url Check - Status code: 404 | https://www.tdwg.org/conferences/2022/session-list/
https://www.tdwg.org/community/citizen-science/pierre.bonnet@cirad.fr | Url Check - Status code: 404 | https://www.tdwg.org/community/citizen-science/
https://www.tdwg.org/standards/bhp-supplementum/ | Url Check - Status code: 404 | https://www.tdwg.org/standards/114
https://www.tdwg.org/conferences/2008/presentation-files/ | Url Check - Status code: 404 | https://www.tdwg.org/conferences/2008/
https://www.tdwg.org/activities/darwincore/ | Url Check - Status code: 404 | http://www.tdwg.org/activities/darwincore/
https://www.tdwg.org/community/species/invasive-organisms/quentin.groom@plantentuinmeise.be | Url Check - Status code: 404 | https://www.tdwg.org/community/species/invasive-organisms/

</body>

</html>

**Comment by gkampmeier** [comment]
@ben-norton I am not sure why some email addresses in <> work as mailto but others don't (and apparently resolve as a webpage link) on [https://www.tdwg.org/conferences/2022/session-list/](https://www.tdwg.org/conferences/2022/session-list/).  I suspect whatever is causing this @peterdesmet, is also causing the other email addresses listed here to fail as mailtos.

**Comment by gkampmeier** [comment]
@ben-norton the website has not been updating properly--it's been reported. @stanblum fixed a number of the issues you provided so GitHub has the correct information now, it's just not being rendered properly yet.  Thanks for finding these issues!

**Comment by ben-norton** [comment]
@gkampmeier It's probably something with markdown syntax. I'm sure Peter and Stan will know.

**Comment by peterdesmet** [comment]
Email addresses can be written as follows:

```
<first.last@example.org>
[First Last](mailto:first.last@example.org>
<mailto:first.last@example.org>
```

They should not be written as:

```
[First Last](first.last@example.org)
[first.last@example.org](first.last@example.org)
```

I've tried to use the first and second approach everywhere, but it seems I missed some. @gkampmeier if you want to be consistent and always include `mailto:` then that is possible too.

**Comment by stanblum** [comment]
I think I've fixed them all, including the redirect to Standard114.  Matt restarted the server, and the redirect works.
