### ISSUE TITLE
Make table of content scrollable

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#494]
Table of contents can be longer than the page height allows (e.g. https://www.tdwg.org/conferences/2022/instructions-for-abstract-submission/). I have recently fixed this in the petridish theme and [pulled it into the tdwg/petridish fork](https://github.com/tdwg/petridish/commit/456628bcb9790ef433da64837861fcd71a40e74a) but the changes are not reflected on the site.

@MattBlissett any idea why? Is there some caching going on with `_sass`? The other recent changes in petridish (e.g. an RSS icon in the footer) _are_ reflected on the site.

**Comment by peterdesmet** [comment]
This is now fixed. Build had a stray `--exclude theme` and did not pull in updates to the theme. Thanks @MattBlissett.

@gkampmeier see e.g. https://www.tdwg.org/conferences/2023/session-list/ : the right-side table of content is now scrollable

**Comment by gkampmeier** [comment]
@peterdesmet in my browser (Chrome based), it only scrolls after the left side exceeds a certain (undetermined) point near the bottom of the page--it does not scroll independently.

**Comment by peterdesmet** [comment]
Debugged with @gkampmeier, is a caching issue.
