### ISSUE TITLE
Setup build server and web hook on GBIF

### ISSUE THREAD

**Issue by timrobertson100** [tdwg/website#5]
GBIF should setup [their Jenkins CI](https://builds.gbif.org/) to build a tdwg-dev.tdwg.org (or similar) site following the [existing documentation](https://github.com/tdwg/website#deployment).

If the documentation is inadequate, this needs to be fixed / have issues lodged.

See #2

**Comment by peterdesmet** [comment]
Although the Pelican generate process should work as it is, the URL of the dev website should become part of the settings for more robust URLs. So, if we can settle on one that would be great.

* Production: `www.tdwg.org`
* Development: most simple (and my preference) is `dev.tdwg.org`, but maybe we have to adopt `dev-www.tdwg.org` or `www-dev.tdwg.org` or similar to avoid name clashes with other prefixes (like `rs`). Do you have a name convention at GBIF?

**Comment by peterdesmet** [comment]
@MattBlissett: the trigger to build should be every commit on the master branch. 🙇

**Comment by MattBlissett** [comment]
I'll make a new VM for this later, for the moment it's using the some one as www.tdwg.org.

search.html is missing from the theme, could you add it so I can test the build?

https://builds.gbif.org/job/tdwg-dev-prod/5/console

**Comment by MattBlissett** [comment]
It will be http://dev.tdwg.org/

**Comment by MattBlissett** [comment]
Should be done.

The callback is only sent from this repository, does it need to be from tdwg-theme too?

**Comment by peterdesmet** [comment]
Awesome! Regarding callback from theme repo: I don't think that's necessary (for now).

**Comment by peterdesmet** [comment]
@MattBlissett found anything missing in the [documentation](https://github.com/tdwg/website#deployment)?

**Comment by MattBlissett** [comment]
No, it worked exactly as described.

**Comment by peterdesmet** [comment]
Great! Closing issue. Thanks again! 🎉
