### ISSUE TITLE
Core Members Revision

### ISSUE THREAD

**Issue by ben-norton** [tdwg/website#505]
**Page(s) where issue occurs**

> https://www.tdwg.org/community/esp/mineralogy/

**Issue description**

> Under Core Members, please replace Sean Moran with Allison Dombrowski  using the following information:
Allison Dombrowski (Collections Manager, Geology) - North Carolina Museum of Natural Sciences, Raleigh, NC, USA
allison.dombrowski@naturalsciences.org

**Comment by stanblum** [comment]
done
