### ISSUE TITLE
Fix description of website technologies in README (pelican no longer used)

### ISSUE THREAD

**Issue by nickynicolson** [tdwg/website#523]
The very first part of the README page for this repo states:
> ... It is generated as a static website with [Pelican](http://docs.getpelican.com/).

The website was updated to use [jekyll](https://jekyllrb.com/) / [petridish](https://github.com/peterdesmet/petridish) so this README needs updating.

**Comment by nickynicolson** [comment]
Github topics labels also need modification

**Comment by stanblum** [comment]
Hi Nicky,   I updated the README, but I'm not sure what you mean about 

> Github topics labels also need modification

Can you elaborate, please?

**Comment by nickynicolson** [comment]
> Hi Nicky, I updated the README, but I'm not sure what you mean about
> 
> > Github topics labels also need modification
> 
> Can you elaborate, please?

Thanks @stanblum! I now see that the README page needs a few more changes, eg there is an annotated directory structure which relates to the old pelican layout rather than jekyll, and there are instructions about running locally which are now outdated. Maybe @peterdesmet could comment about how best to update these with reference to documentation already existing in [petridish](https://github.com/peterdesmet/petridish)?

The github repo labels are configured in the about panel - displayed mid-right on the repo homepage. If you're an admin you should see a gear icon which allows you to modify the about text for the repo and select "labels" which are shown as pilled text. Currently for the TDWG website these are "pelican" and "tdwg" & pelican is of course out of date.

**Comment by peterdesmet** [comment]
Thanks @nickynicolson

- I have updated the topic to `Jekyll`
- I have updated the README to reflect the Jekyll setup. Can you have a look at https://github.com/tdwg/website/pull/525 and provide feedback?
