### ISSUE TITLE
Build to update task group statuses failed

### ISSUE THREAD

**Issue by baskaufs** [tdwg/website#527]
@peterdesmet Could you please take a look at the changes I made in https://github.com/tdwg/website/pull/526 ? The build https://builds.gbif.org/job/tdwg-website/lastBuild/ failed, so clearly I did something wrong.

**Comment by baskaufs** [comment]
@peterdesmet I have recovered the Markdown only text changes that I made in the pull request https://github.com/tdwg/website/pull/526. Once @stanblum merges those changes in https://github.com/tdwg/website/pull/530, then could you please make the required changes in the navigation structure to reflect the IG/TG reorganization:

- [ ] Move the [Plant Phenology TG](https://www.tdwg.org/community/osr/phenology/) from under the OSR IG on the Community Page to be under the Darwin Core MG.
- [ ] On the [DwC MG page](https://www.tdwg.org/community/dwc/) add the Plant Phenology TG to the list of task groups chartered under it (the page does not yet have a task group list).
- [ ] On the [OSR IG page](https://www.tdwg.org/community/osr/), remove the Plant Phenology TG from the list of task groups chartered under it.
- [ ] Move the Plant Phenology page from the OSR directory to the DwC directory.

These are the navigational structure changes that I tried to do when I caused the build to fail, so I am reluctant to try doing it again myself.

**Comment by peterdesmet** [comment]
Will do, @stanblum can you ping me once the changes in #526 and #530 are live?

**Comment by baskaufs** [comment]
The #526 changes were reverted, so they are no longer active. The #530 changes recover some of those reverted changes.

**Comment by stanblum** [comment]
The PR #530 was merged and built successfully.

Peter, If you don't have time to do this in the next few days, let me know
and I will try.

Thank you both!

**Comment by peterdesmet** [comment]
With the handy checklist @baskaufs provided, my work is easy. 😄 See PR https://github.com/tdwg/website/pull/532

**Comment by peterdesmet** [comment]
@baskaufs PR accepted. I'll let you review the website and close this issue.

**Comment by stanblum** [comment]
The build succeeded!

**Comment by baskaufs** [comment]
Yay!
