### ISSUE TITLE
Indicate commit hash on website

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#6]
For reference, it would be cool if the commit hash (in dev) and/or release version (in prod) on which the build is based is indicated in the footer of the website. Not sure yet how to do that, but noting it here as an idea.

**Comment by gkampmeier** [comment]
Is that needed if you are distinguishing the difference by the URL (see #5)? Or am I misunderstanding something?

**Comment by MattBlissett** [comment]
`git describe` gives the tag (for a release) or tag+hash (otherwise).

It could go into settings*.py or wherever else might be appropriate.

**Comment by peterdesmet** [comment]
@gkampmeier: the difference in URL is the difference between the development website (where everything can be considered a preview of what's to come) and the actual (production) website (which will often be a bit behind until the editor has approved stuff). The hash on the other had is just a handy reference to know on which commit the site is based: it could help to figure out "Hey, why am I not seeing these changes on the site yet? Oh right, it's based on this version." For the dev site we want it to always be based on the most recent commit, so if that's not the case it indicates a problem (which is useful to know)

@MattBlissett: it would have to be something that's automatically added. The settings are static (= manually updated). Will see later how that can be done.

**Comment by MattBlissett** [comment]
Given a line like

```
GIT_HASH="unknown"
```

in settings-dev.py / settings-prod.py, I'd add a line to the build process like

```
perl -pi -e "s/GIT_HASH=.*/GIT_HASH=\""`git describe`\""/" settings-dev.py settings-prod.py
```

It needs one tag to start.  The result would be something like

```
GIT_HASH="0.0.1-1-g9261a7e"
```

**Comment by peterdesmet** [comment]
This is similar to the idea regarding showing the last modified date (#136). Closing as duplicate.
