### ISSUE TITLE
Create contributing guide

### ISSUE THREAD

**Issue by gkampmeier** [tdwg/website#8]
On the opening page [https://github.com/tdwg/website](https://github.com/tdwg/website), the links to the contributing guides 404

**Comment by peterdesmet** [comment]
I'm aware. 😄 I still need to write it. Will rename this issue as a task.

**Comment by peterdesmet** [comment]
_This is an old issue regarding the TDWG (Pelican) website. I am trying to clean those up._

The contributing guide is available at https://www.tdwg.org/about/website-faq/ That pages is also referenced in:

https://github.com/tdwg/website/blob/2a6129d1b334fd0d69e336da0910c7d85035e098/.github/CONTRIBUTING.md?plain=1#L1-L3

The guide should be updated, but there is a separate issue for that: #483
