### ISSUE TITLE
Testing page on dev server

### ISSUE THREAD

**Issue by peterdesmet** [tdwg/website#9]
Just did a commit to test build server: https://github.com/tdwg/website/commit/5fb7b037511687e27cb772a5574cba93407ba6fd and the build server indicates a successful build, but the site indicates a test page: http://dev.tdwg.org/

PS: can the URL of the build server be public (as in: part of the documentation)?

**Comment by MattBlissett** [comment]
The build log says `ERROR: Unknown status 'draft' for file pages/home.md, skipping it.`

index.html wasn't generated, so you're seeing the default Apache page.

The build system is already public for other GBIF projects, so it can be public for this.

**Comment by MattBlissett** [comment]
I don't think `settings-dev.py` is working as intended.  

```
$ pelican -s settings.py
WARNING: Feeds generated without SITEURL set properly may not be valid
Done: Processed 1 article, 0 drafts, 4 pages and 0 hidden pages in 0.23 seconds.

$ pelican -s settings-dev.py
WARNING: Feeds generated without SITEURL set properly may not be valid
ERROR: Unknown status 'draft' for file pages/home.md, skipping it.
Done: Processed 1 article, 0 drafts, 3 pages and 0 hidden pages in 0.20 seconds.
```

**Comment by peterdesmet** [comment]
Ok, thanks. Will look into this on Monday.

**Comment by MattBlissett** [comment]
You now have SSH access, using the SSH key you provided to GitHub, as pdesmet@dev.tdwg.org.

`sudo` should be used if you need to do something as root. Other than looking at log files or restarting HTTPD, I'd prefer to know when anything needs to be changed.

**Comment by peterdesmet** [comment]
Thanks, noticed console output is public at https://builds.gbif.org/job/tdwg-dev-prod/16/console. Will let you know when I'll need to use ssh.
