### ISSUE TITLE
Fix link to github in content/pages/community/tnc/index.md

### ISSUE THREAD

**Issue by ghwhitbread** [tdwg/website#90]
**Page(s) where issue occurs**

> 
https://github.com/tdwg/website/blob/master/content/pages/community/tnc/index.md

**Issue description**

LInk to github in community page attempts to link to standard rather than tdwg/tnc repository.  This is probably a good idea (we can link to tnc from there) but that link needs to be corrected:  (https://github.com/tdwg/standards/tcs) should be https://github.com/tdwg/tcs.

**Comment by stanblum** [comment]
I think the link to GitHub on the Community/ TNC (IG) page should actually point to the GitHub TNC repo.  So that's what I've done.  At least now, it doesn't 404.
